version: "3.1"
services:
  web:
    image: cdshub/nginx-react:0.1
    restart: always
    volumes:
      - ./build:/usr/share/nginx/html/:delegated
    ports:
      - "${PUBLIC_PORT:-80}:80"
    expose:
      - 80
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: webmaster@cdstean.com
networks:
  default:
    external:
      name: ${NETWORK:-webproxy}